# -*- mode: ruby -*-
# frozen_string_literal: true

# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # hostname inside the VM
  config.vm.hostname = "utm"
  config.vm.provider :utm do |utm|
    # Name in UTM UI
    utm.name = "vagrant"
    # UTM VM file
    utm.utm_file_url = "https://github.com/naveenrajm7/utm-box/releases/download/debian-12.6/debian-12.6.0-arm64-netinst-vagrant.zip"
    utm.memory = 512
    utm.cpus = 2
    # Wait time in secs for VM to be running after 'started'
    utm.wait_time = 22
  end
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2
  SHELL
end
