# -*- mode: ruby -*-
# frozen_string_literal: true

# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :utm do |utm|
    # TODO: pass this to UTM file setting in the provider
    utm.name = "vagutm"
    utm.utm_file = "/Users/naveenrajm/Developer/UTMvagrant/DebianTest.utm"
  end
end
