# -*- mode: ruby -*-
# frozen_string_literal: true

# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "utm/debian11"
  config.vm.box_version = "0.0.1"
  # hostname inside the VM
  config.vm.hostname = "utm"
  config.vm.network "forwarded_port", guest: 80, host: 8989
  config.vm.provider :utm do |utm|
    # Name in UTM UI
    # utm.name = "debian"
    utm.memory = 512
    utm.cpus = 1
    utm.notes = "Vagrant: For testing plugin development"
    # Wait time in secs for VM to be running after 'started'
    # Currently, not used and we rely on the built-in wait for communicator(ssh) to be ready
    utm.wait_time = 22
    # QEMU Directoy Share mode for the VM
    utm.directory_share_mode = "webDAV"
  end
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2
  SHELL
end
